spring:
  application:
    name: spring-ms
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:43109}


  port: ${APPLICATION_PORT:8082}

custom:
  communication:
    topicName: ${KAFKA_TOPIC_NAME:cars}

