apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    {{- include "microservice2.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.config.environment }}
{{ $key | indent 2 }}: {{ $val | quote }}
{{- end }}

